### PR TITLE
Fix support for non-null assertinon

### LINKED ISSUE #69: Doesn't suggest with non-null assertion at the end
example:
`test!.const` should be the same as `test.const`

Just saw you've fixed a bug, so there is a new one!
By the way thank you for your work, this one is on top of my time-saving extensions!

### PR DESCRIPTION
**Pull request by zardoy**
fixes #69 

isk wether I should add more tests

### CODE REVIEW

File: src/postfixCompletionProvider.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ export class PostfixCompletionProvider implements vsc.CompletionItemProvider {
     try {
       return this.templates
         .filter(t => {
-          let canUseTemplate = t.canUse(currentNode)
+          let canUseTemplate = t.canUse(ts.isNonNullExpression(currentNode) ? currentNode.expression : currentNode)
```
Comment (zardoy) [inline src/postfixCompletionProvider.ts:52]: I didn't find more elegant solution (without introducing a lot of code changes). since most checks like `inReturnStatement` traverses recursively it doesn't seem to break anything

Comment (ipatalas) [reply src/postfixCompletionProvider.ts:52]: All tests are passing so I think it doesn't ;)
Not a perfect solution but not very bad as well. Good enough if it fixes the problem. It will be still very easy to improve that later in the future so this looks good to me.

**Review by ipatalas — APPROVED** [review]
